sudo: required
language: c
services:
  - docker
before_install:
  - docker pull bitcraze/builder
script:
  # Build CF2 basic
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=CF2

  # Build CF2 with "all" features enabled
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=CF2 DEBUG=1 "EXTRA_CFLAGS=-DCALIBRATED_LED_MORSE -DIMU_TAKE_ACCEL_BIAS -DIMU_MPU6500_DLPF_256HZ -DMADWICK_QUATERNION_IMU -DDEBUG_QUEUE_MONITOR"

  # Build CF1
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=CF1

  # Build CF1 with "all" features enabled
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build clean
  - docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build PLATFORM=CF1 DEBUG=1
